version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    logging:
      driver: none

  redis:
    container_name: redis
    image: redis:6.0.9-alpine3.12
    logging:
      driver: none

  django:
    container_name: django
    build: ./
    volumes:
      - ./src:/src:rw
      - ./.env:/src/core/.env
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      MODE: DEV_DJANGO
      POSTGRES_HOST: postgres
      POSTGRES_DB: 5432
      test: pytest -vs
